/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTypesIndexRouteImport } from './routes/_app/types/index'
import { Route as AppListsIndexRouteImport } from './routes/_app/lists/index'
import { Route as AppListsListIdRouteImport } from './routes/_app/lists/$listId'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppTypesIndexRoute = AppTypesIndexRouteImport.update({
  id: '/types/',
  path: '/types/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppListsIndexRoute = AppListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppListsListIdRoute = AppListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/lists/$listId': typeof AppListsListIdRoute
  '/lists/': typeof AppListsIndexRoute
  '/types/': typeof AppTypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/lists/$listId': typeof AppListsListIdRoute
  '/lists': typeof AppListsIndexRoute
  '/types': typeof AppTypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/lists/$listId': typeof AppListsListIdRoute
  '/_app/lists/': typeof AppListsIndexRoute
  '/_app/types/': typeof AppTypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lists/$listId' | '/lists/' | '/types/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lists/$listId' | '/lists' | '/types'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/lists/$listId'
    | '/_app/lists/'
    | '/_app/types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/types/': {
      id: '/_app/types/'
      path: '/types'
      fullPath: '/types/'
      preLoaderRoute: typeof AppTypesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/lists/': {
      id: '/_app/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AppListsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/lists/$listId': {
      id: '/_app/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AppListsListIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppListsListIdRoute: typeof AppListsListIdRoute
  AppListsIndexRoute: typeof AppListsIndexRoute
  AppTypesIndexRoute: typeof AppTypesIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppListsListIdRoute: AppListsListIdRoute,
  AppListsIndexRoute: AppListsIndexRoute,
  AppTypesIndexRoute: AppTypesIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
